
test_name: "Online_RewardsSlow" # name params
architecture: "slow"

set_n: 1
n: 1

# agent training parameters
train_mode: "Online"
test_mode: "Std"

n_train_steps: 6000
n_test_laps: 20

noise_std: 0
max_speed: 2

filter: False

n_scans: 2
random_seed: 10000

map_name: "f1_esp"

runs:
  - reward: "Zero"
  - reward: "Cth"
  - reward: "Progress"
  - reward: "Velocity"
