
test_name: "Online_RewardsFast" # name params
architecture: "fast"

set_n: 1
n: 5

# agent training parameters
train_mode: "Online"
test_mode: "Std"

n_train_steps: 10000
n_test_laps: 20

noise_std: 0
max_speed: 5

filter: False

n_scans: 2
random_seed: 10000
reward: "Velocity"

runs:
  - map_name: "f1_esp"
  - map_name: "f1_aut"
  - map_name: "f1_mco"
  - map_name: "f1_gbr"
