
test_name: "PP_TestMaps" # name params
architecture: "PP"
raceline: True
pp_speed_mode: "raceline"

set_n: 1
n: 2

# agent training parameters
train_mode: "PP"
test_mode: "Std"

n_test_laps: 2

noise_std: 0
max_speed: 5

filter: False

n_scans: 2
random_seed: 10000
reward: "PP"
n_train_steps: 10000

runs:
  - map_name: "f1_esp"
  - map_name: "f1_mco"
  - map_name: "f1_aut"
  - map_name: "f1_gbr"
