
# Run with PP and rando

architecture: "PP"
raceline: True
pp_speed_mode: "raceline"
test_name: "SSS_ppValidation"
filter: False
n_test_laps: 5

set_n: 1
n: 1

train_mode: "Std"
test_mode: "Super"


noise_std: 0
n_scans: 1
random_seed: 1000

# map_name: "f1_mco"
map_name: "f1_gbr"
# map_name: "f1_aut"
# map_name: "f1_esp"

runs:
  - max_speed: 3
    test_mode: "Super"
  - max_speed: 4
    test_mode: "Super"
  - max_speed: 5
    test_mode: "Super"
  - max_speed: 6
    test_mode: "Super"

  - max_speed: 3
    test_mode: "Std"
  - max_speed: 4
    test_mode: "Std"
  - max_speed: 5
    test_mode: "Std"
  - max_speed: 6
    test_mode: "Std"





