
test_name: "Std_TrainSpeeds" # name params
architecture: "fast"

set_n: 1
n: 5

# agent training parameters
train_mode: "Std"
test_mode: "Std"

n_test_laps: 20

noise_std: 0

filter: False
n_train_steps: 100000

n_scans: 2
random_seed: 10000
reward: "Cth"
map_name: "f1_esp"

runs:
  - max_speed: 3
  - max_speed: 4
  - max_speed: 5
  - max_speed: 6